#!/bin/bash
comm=$1
group=$2
name=$3

default() {
	echo "Please enter valid instructions"
	echo "  password <command> <group> <name>"
	echo "  Commands:"
	echo "    init - initialize (only run once)"
	echo "    add - add a password"
    echo "    list - list password"
	echo "    remove - remove password "
	echo "    newgroup - create a new group"
	echo "    listgroup - list groups"
    echo "    remgroup - delete group"
}

add() {
	echo "Adding new password"
	echo "Enter name: "
	read newname
	echo "Enter Description: "
	read desc
	echo "Password: "
	read password
	query="insert into ${group} (name,description,password) values ('${newname}','${desc}','${password}')"
	echo $query | mysql passwords
}

list() {
	query="select id,name,password,description from ${group}"
	echo $group
	echo $query
	echo $query | mysql passwords
}

remove() {
	query="delete from $group where name='$name'"
	echo $query | mysql passwords
}

newgroup() {
	query="create table $group (id int auto_increment not null, name varchar(50) not null, description varchar(255), password varchar(20) not null, primary key(id))"
	echo $query | mysql passwords
}

listgroup() {
	query="show tables"
	echo $query | mysql passwords
}

remgroup() {
	query="drop table $group"
	echo $query | mysql passwords
}

init() {
	query="create database passwords"
	mysql < echo $query
}

case $comm in
	init)
		init
	;;
	add)
		add
	;;
	list)
		list
	;;
	remove)
		remove
	;;
	newgroup)
		newgroup
	;;
	listgroup)
		listgroup
	;;
	remgroup)
		remgroup
	;;
	*)
		default
	;;
esac
